version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "automerge"
    # Limit the number of open pull requests for version updates
    open-pull-requests-limit: 10
    # Set version update strategy
    versioning-strategy: auto
    # Allow up to 5 concurrent pull requests for dependencies
    pull-request-branch-name:
      separator: "-"
    # Configure automatic merging
    automatic-rebase-strategy: auto
    # Group dependency updates
    groups:
      development-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "jest*"
          - "cypress*"
      production-dependencies:
        patterns:
          - "react*"
          - "next*"
          - "@prisma/*"
